<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Contracts\**" />
    <Compile Remove="DTOs\**" />
    <EmbeddedResource Remove="Contracts\**" />
    <EmbeddedResource Remove="DTOs\**" />
    <None Remove="Contracts\**" />
    <None Remove="DTOs\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Patient.Infrastructure\Patient.Infrastructure.csproj" />
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Contracts\Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Google.Protobuf" Version="3.33.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
    <PackageReference Include="Grpc.Tools" Version="2.76.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.7" />
    <PackageReference Include="FluentValidation" Version="11.9.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="MassTransit.Abstractions" Version="8.3.2" />
  </ItemGroup>




</Project>
