services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - hemalink-net

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - hemalink-net

  iam.api:
    build:
      context: .
      dockerfile: iam.Dockerfile
    container_name: iam.api
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ConnectionStrings__LabIAM: "Host=postgres;Port=5432;Database=LabIAM;Username=postgres;Password=yourpassword;"
      Redis__ConnectionString: "redis:6379"
      Jwt__Issuer: "lab-iam"
      Jwt__Audience: "lab.api"
      Jwt__SigningKey: "Jx6n2QvB5pTf8Kz3Wm9aS4Ld7Yh0Nr2Xu8Cj5Pk1Vg3Mz7Rb0Hq4Tn6Wy8Le2"
      Jwt__AccessTokenMinutes: "60"
      Jwt__RefreshTokenDays: "14"
      Auth__Google__ClientId: "1037103717152-a63mvuqkkainigu8q232knqpbmci430v.apps.googleusercontent.com"
      Email__ResetPasswordBaseUrl: "http://hema-link.io.vn/reset-password"
    depends_on:
      - postgres
      - redis
    ports: [ "5001:5001" ]
    networks:
      - hemalink-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  patient.api:
    build:
      context: .
      dockerfile: patient.Dockerfile
    container_name: patient.api
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__PatientService4: "Host=postgres;Port=5432;Database=PatientService4;Username=postgres;Password=yourpassword;"
      Grpc__IamUrl: "http://iam.api:5001"
      Jwt__Issuer: "lab-iam"
      Jwt__Audience: "lab.api"
      Jwt__SigningKey: "Jx6n2QvB5pTf8Kz3Wm9aS4Ld7Yh0Nr2Xu8Cj5Pk1Vg3Mz7Rb0Hq4Tn6Wy8Le2"
      PATIENT_PII_KEYS: |
        FES03/bBdxXAmpgtDTccC15qDWd112gVLcksrZEib98=
        8wCAUQo+Bggcq7suyJ2io37vmFLjOORzl7RMbhmipR0=
        W2mPvA+pi08SJGTUV43coZxqWVNP3guFg0puMHW4jdc=
    depends_on:
      - postgres
      - iam.api
    ports: [ "5002:5002" ]
    networks:
      - hemalink-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api.gateway:
    build:
      context: .
      dockerfile: gateway.Dockerfile
    container_name: api.gateway
    depends_on:
      - iam.api
      - patient.api
      - blogservice.api
    ports: [ "8080:8080" ]
    networks:
      - hemalink-net

  notify.api:
    build:
      context: .
      dockerfile: deployments/docker/Notify.Dockerfile
    container_name: notify.api
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5601"
      ConnectionStrings__Notify: "Host=postgres;Port=5432;Database=notify;Username=postgres;Password=yourpassword;"
      Redis__ConnectionString: "redis:6379"
      Email__Smtp__Host: "smtp.gmail.com"
      Email__Smtp__Port: "587"
      Email__Smtp__UseStartTls: "true"
      Email__Smtp__User: "managermentlabolary@gmail.com"
      Email__Smtp__Password: "qivyvznissngdvhn"
      Email__Smtp__From: "managermentlabolary@gmail.com"
    depends_on:
      - postgres
      - redis
    ports: [ "5601:5601" ]
    networks:
      - hemalink-net

  testorder.api:
    build:
      context: .
      dockerfile: testorder.Dockerfile
    container_name: testorder.api
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      TZ: Asia/Ho_Chi_Minh
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=TestOrderDB;Username=postgres;Password=yourpassword;"
      Redis__ConnectionString: "redis:6379"
      Jwt__Issuer: "lab-iam"
      Jwt__Audience: "lab.api"
      Jwt__SigningKey: "Jx6n2QvB5pTf8Kz3Wm9aS4Ld7Yh0Nr2Xu8Cj5Pk1Vg3Mz7Rb0Hq4Tn6Wy8Le2"
      AiSettings__ApiKey: "AIzaSyBLC2osUesI35WN6qaRiSbkzCk3d5lShL4"
      AiSettings__ModelName: "gemini-2.5-flash"
    depends_on:
      - postgres
      - redis
    ports:
      - "5003:5003"
    networks:
      - hemalink-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  blogservice.api:
    build:
      context: .
      dockerfile: deployments/docker/BlogService.Dockerfile
    container_name: blogservice.api
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=BlogServiceDB;Username=postgres;Password=yourpassword;"
      Jwt__Issuer: "lab-iam"
      Jwt__Audience: "lab.api"
      Jwt__SigningKey: "Jx6n2QvB5pTf8Kz3Wm9aS4Ld7Yh0Nr2Xu8Cj5Pk1Vg3Mz7Rb0Hq4Tn6Wy8Le2"
    depends_on:
      - postgres
    ports: [ "5004:5004" ]
    networks:
      - hemalink-net
    volumes:
      - ./BlogService.Presentation/Images:/app/Images
    extra_hosts:
      - "host.docker.internal:host-gateway"

  instrument.api:
    build:
      context: .
      dockerfile: instrument.Dockerfile
    container_name: instrument.api
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ConnectionStrings__InstrumentDb: "Host=postgres;Port=5432;Database=InstrumentDB;Username=postgres;Password=yourpassword;"
      TestOrderBaseUrl: "http://testorder.api:5003"
      Jwt__Issuer: "lab-iam"
      Jwt__Audience: "lab.api"
      Jwt__SigningKey: "Jx6n2QvB5pTf8Kz3Wm9aS4Ld7Yh0Nr2Xu8Cj5Pk1Vg3Mz7Rb0Hq4Tn6Wy8Le2"
    depends_on:
      - postgres
    ports: [ "5008:5008" ]
    networks:
      - hemalink-net
    volumes:
      - ./Instrument.Presentation/Images:/app/Images
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pg_data:

networks:
  hemalink-net:
    driver: bridge
